name: CI/CD Dokploy Deployment (avec GHCR)

on:
  push:
    branches:
      - main

# Définissez les permissions minimales.
# 'packages: write' est nécessaire pour pousser vers GHCR.
permissions:
  packages: write
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Utilisez une seule job nommée 'deploy' pour orchestrer toutes les étapes.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Étape 1: Configuration des Variables (Tag de l'Image) ---
      # Nous définissons l'IMAGE_TAG pour qu'elle soit disponible dans les étapes suivantes.
      - name: Set up Image Variables for GHCR
        id: vars
        run: |
          # Le format requis est : ghcr.io/ORGANIZATION_OR_USER/REPOSITORY_NAME:latest
          # Example for LeyInvest: ghcr.io/evandjefie/leyinvest:latest
          IMAGE_TAG="ghcr.io/${{ github.repository }}:latest"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Image Tag set to: $IMAGE_TAG"

      # --- Étape 2: Connexion au GitHub Container Registry (GHCR) ---
      # Utilise le GITHUB_TOKEN par défaut qui a les permissions nécessaires.
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }} 

      # --- Étape 3: Build et Push de l'image vers GHCR ---
      # Utilise l'IMAGE_TAG définie à l'étape 1.
      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}

      # --- Étape 4: Déploiement sur Dokploy ---
      # Utilise l'action Dokploy pour déclencher un redéploiement
      # avec la nouvelle image (spécifiée par l'application ID et le tag par défaut).
      # Note: Cette action Dokploy utilise le tag 'latest' implicitement 
      # ou doit être configurée pour accepter le tag GHCR.
      # L'action benbristow/dokploy-deploy-action permet de passer le tag 
      # via l'argument `image_tag`. Je l'ajoute pour la clarté et la flexibilité.
      - name: Dokploy Deployment
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          # Les variables GH Actions sont toujours appelées par secrets.NAME
          auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          image_tag: ${{ env.IMAGE_TAG }}
