name: CI/CD Dokploy Deployment (avec GHCR)

on:
  push:
    branches:
      - main

# Définissez des permissions minimales pour le GITHUB_TOKEN si nécessaire,
# mais 'write' aux packages est nécessaire pour pousser vers GHCR.
permissions:
  packages: write
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Configuration GHCR ---
      
      # 1. Définition du nom de l'image (format GHCR)
      - name: Set up Image Variables for GHCR
        id: vars
        run: |
          # Le nom de l'image doit être : ghcr.io/ORGANIZATION_OR_USER/REPOSITORY_NAME
          # Exemple : ghcr.io/${{ github.repository_owner }}/mon-app
          IMAGE_TAG="ghcr.io/${{ github.repository }}:latest"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 2. Connexion au GitHub Container Registry (GHCR)
      # Le GITHUB_TOKEN est utilisé par défaut, il a le scope nécessaire.
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Utilisateur ou organisation qui déclenche l'action
          password: ${{ secrets.GITHUB_TOKEN }} # Token de l'Action GitHub (scopes automatiques)

      # 3. Build et Push de l'image vers GHCR
      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          # (Optionnel) Si vous utilisez un Dockerfile custom : file: ./path/to/Dockerfile

      # 4. Déclenchement du Déploiement via l'API Dokploy
      # Assurez-vous que le champ "Image Docker" dans Dokploy est réglé sur ${{ env.IMAGE_TAG }} (ex: ghcr.io/org/repo:latest)
      - name: Dokploy Deployment Trigger
        uses: benbristow/dokploy-deploy-action@v0.0.1
        with:
          auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
